name: hello_word
description: Hello world application

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  english_words: ^3.1.5
  carousel_pro: ^1.0.0
  http: ^0.12.2
  google_fonts: ^1.1.0
  shimmer: ^1.1.1
  simple_animations: ^2.2.1
  fluttertoast: ^7.0.2
  flutter_slidable: ^0.5.5
  firebase_auth: ^0.18.0+1



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/image/header2.jpg
    - assets/image/logo3.png
    - assets/image/logo.png
    - assets/image/atgt.jpg
    - assets/image/atgt1.jpg
    - assets/image/atgt2.jpg
    - assets/image/atgt3.jpg
    - assets/image/xpgt.png
    - assets/image/btgt.png
    - assets/image/tndc.png
    - assets/image/gplx.png
    - assets/image/tintuc.png
    - assets/image/gioithieu.png
    - assets/image/lienhe.png
    - assets/image/xemay1.png
    - assets/image/xemay2.png
    - assets/image/xemay3.png
    - assets/image/xemay4.png
    - assets/image/xemay5.png
    - assets/image/xemay6.png
    - assets/image/nen1.jpg
    - assets/image/bienbaocam1.png
    - assets/image/bienbaocam2.png
    - assets/image/bienbaocam3.png
    - assets/image/bienbaocam4.png
    - assets/image/bienbaocam5.png
    - assets/image/bienchidan1.png
    - assets/image/bienchidan2.png
    - assets/image/bienchidan3.png
    - assets/image/bienchidan4.png
    - assets/image/abc.PNG
    - assets/image/background.png
    - assets/image/clock.png
    - assets/image/light-1.png
    - assets/image/light-2.png
    - assets/image/cauhoi1.jpg
    - assets/image/cauhoi2.jpg
    - assets/image/cauhoi3.jpg
    - assets/image/cauhoi4.jpg
    - assets/image/cauhoi5.jpg
    - assets/image/cauhoi6.jpg
    - assets/image/cauhoi7.jpg

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf



  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
